### ISSUE TITLE
Retail: Macro Generates Incorrectly

### ISSUE THREAD

**Issue by FilthySerf** [fubaWoW/fuba_MageFoodMacro#1]
I noticed today that the macro on retail generates incorrectly.

#showtooltip item:113509
/use [btn:2]Conjure Refreshmentitem:113509

This is how it generates, which doesn't let the macro work. I have to manually go back and add ; between refreshment and item to get it to work.

#showtooltip item:113509
/use [btn:2]Conjure Refreshment;item:113509

Not sure when this started as it's been a while since I've played my mage.

**Comment by fubaWoW** [comment]
fixed in https://github.com/fubaWoW/fuba_MageFoodMacro/commit/290add161eab41decf8684bc65e3459432a50e5d
thanks for the info! 👍
